if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs     
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim   
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC 
endif

call plug#begin('~/.vim/plugins')
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'w0rp/ale'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'leshill/vim-json'
call plug#end()

set tabstop=2
set shiftwidth=2
set noswapfile
set copyindent
