" initialize vim plug and load plugins
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs     
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim   
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC 
endif

call plug#begin('~/.vim/plugins')
Plug 'scrooloose/nerdtree'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'w0rp/ale'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'leshill/vim-json'
Plug 'othree/yajs.vim'
Plug 'othree/es.next.syntax.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-airline/vim-airline'
call plug#end()

" general editor preferences
set backspace=2
set tabstop=2
set shiftwidth=2
set expandtab
set noswapfile
set copyindent
set relativenumber
set nowrap
set mouse=a

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" tabbed browsing
nnoremap tn :tabnew<Space>
nnoremap th :tabfirst<Cr>
nnoremap tj :tabprev<Cr>
nnoremap tk :tabnext<Cr>
nnoremap tl :tablast<Cr>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

map <c-z> u
imap <c-z> <ESC> u i
map <c-s> :w <Enter>
imap <c-s> <ESC> :w <Enter> 

" nerdtree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1
let NERDTreeShowHidden = 1
let NERDTreeHijackNetrw = 1
autocmd StdinReadPre * let s:std_in=1 
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" youcompleteme
set encoding=utf8
